### ISSUE TITLE
Error after editing input.dat through R

### ISSUE THREAD

**Issue by nicolettebell** [remi-daigle/marxanr#2]
Currently trying to optimise inputs for a dataset in an R for loop and running into an error message when editing BLM (and only BLM, edits to NUMITNS, SCENNAME, Input Files, and NUMREPS all work without a hitch).

Method: the input.dat file is read in using read.delim and the BLM value [2,1] is edited (same syntax as if editing manually through e.g. notepad) and rewritten using write.table again as a .dat file.

Issue: Once the input file is rewritten and Marxan is run in R using runMarxan, the following error appears and the script ends: 
"Invalid parameter type for given param BLM. Expecting type: d 
Error during Marxan execution."

**Comment by remi-daigle** [comment]
Is this an issue with the `runMarxan()` function? i.e. if you run Marxan manually with your edited input.dat file, do you get the same error? Or is this a problem with how you're editing your input.dat?

Alternatively, instead of using read.delim, could you use this package's [`newParams()`](https://remi-daigle.github.io/marxanr/reference/newParams.html) and [`writeParams()`](https://remi-daigle.github.io/marxanr/reference/writeParams.html) functions? The `newParams()` has a bunch of default values that you can see in the documentation or by running the function with no arguments, but you can customize it by, for example, setting the BLM in the arguments OR editing the R object. e.g.:



```
scen <- "MarxanTest"

# create new input parameters and write it out:
input <- newParams(BLM = 2, SCENNAME = scen, PUVSPRNAME = "puvsp.dat")
writeParams(inputdat = input, file = "input_demo.dat")

# edit input 'manually' and write it out again
input@BLM <- 100 
writeParams(inputdat = input, file = "input_demo_modified.dat")

```

Does this solve your problem?

**Comment by nicolettebell** [comment]
newParams and writeParams ended up throwing the same message, but after some trial and error I determined that the issue resulted from trying to save Marxan's outputs to an output folder which started with "BLM".

The syntax I was using to rename the folder for each loop was
`i=5
newinput <- newParams(BLM = i, OUTPUTDIR = paste0("output/BLM_OPT/test"i))
writeParams(newinput, file = "input.dat")` 
before using runMarxan, but changing "BLM_OPT" to "B_OPT" has solved it. 

I've never run across this issue in R before, so not sure if it's a language/user issue or a package issue, but if it's the former happy for you to close this and thank you for your help!

**Comment by remi-daigle** [comment]
Interesting! This is actually a Marxan software issue (that I had no idea existed), not an issue with this package or R.

Based on your situation, I'm going to add a warning to in the R package that Marxan won't like it if you use "BLM" in the `OUTPUTDIR`. I'll close this issue once I've done the above. Thank you for submitting your issue!

EDIT: Marxan also only dislikes the use of all caps 'BLM', i.e. 'blm' works fine in `OUTPUTDIR`
